### ISSUE TITLE
Power status update

### ISSUE THREAD

**Issue by davyverstaen** [mhaid/de.mhaid.panasonicTVIP#4]
Hey,

is it possible to add the functionality that the app automatically updates the power status of the Panasonic device. The app works great but if somebody in the family uses the remote the power status does not update in the app.

Kind regards,

Davy

**Comment by mhaid** [comment]
Hey Davy,

thank you for the interest in the Panasonic-App!

I just implemented a feature, which checks the TVs status every 5 minutes. As soon as I have tested the update, I'll upload it onto the appstore and notify you here 👍 

Cheers,
Morris

**Comment by mhaid** [comment]
Hey Davy,

the update is now submitted and will be checked by Athom soon. It should be publicly available next week. 
If you want to update now, you can do so here:
https://homey.app/de-de/app/de.mhaid.panasonicTVIP/Panasonic-TV-IP-Viera/test/

If you got any questions or problems, feel free to create a new issue here on github.

Cheers,
Morris
