### ISSUE TITLE
Homey v5

### ISSUE THREAD

**Issue by JerryVdV** [mhaid/de.mhaid.panasonicTVIP#8]
Hi, loving the app - so thanks a lot.
I’ve got a question, are you planning on making a version for Homey v5?

**Comment by mhaid** [comment]
Hello Jerry,
thank you for your interest. It is planned to update the app to support V5, in fact I just uploaded a test-version to the appstore.
It's not tested yet, but you're very welcome to install it. If you do, I'd be happy if you could briefly let me know if everything worked for you:
https://homey.app/de-de/app/de.mhaid.panasonicTVIP/Panasonic-TV-IP-Viera/test/

Best regards,
Morris

**Comment by JerryVdV** [comment]
Thanks, will update Homey when I get home and install the app.

Best,
Jerry

**Comment by JerryVdV** [comment]
Hi Morris,

The current TV device that was installed with the prior app gives the following error when a command is given:
[invalid_device]

When I try to install a new tv device I get the following error:
missing ) after argument list

Best,
Jerry

**Comment by mhaid** [comment]
Okay, thats a bit strange. Unfortunatly I can't test it out on V5 myself, as some of the apps I use do not support V5 yet...

Could you submit a crash-report so I can have a closer look?

You can do that by navigation to the following menu in the Homey-App:
_More (Navigation bar on the bottom)-> Apps -> Panasonic TV IP Viera -> Setting-Symbol -> Create diagnostic report -> Enter some kind of text (min. 11-characters and not really relevant)_

**Comment by JerryVdV** [comment]
Done, refer to
bddb3fd1-e188-4ce7-9fae-a75fdc3b3f58

**Comment by mhaid** [comment]
I just uploaded a new test-version to the appstore. The bug should hopefully be fixed

**Comment by JerryVdV** [comment]
Awesome, looking forward to test it!
Thanks

**Comment by mhaid** [comment]
Sorry, I just noticed that I didn't publish the draft to the appstore.
But now it is available :)

https://homey.app/de-de/app/de.mhaid.panasonicTVIP/Panasonic-TV-IP-Viera/test/

**Comment by JerryVdV** [comment]
Haha, no problem.
Just tested it again, appears to have similar issues.

Refer to:
31c2e82a-4f7b-449d-bd0e-bec0e84d69a2

**Comment by mhaid** [comment]
All right, missed an occurrence, I guess.
Uploaded the updated version to the appstore. Hopefully fixed now...

**Comment by JerryVdV** [comment]
33451863-8296-4acf-a98c-ce60172930ce

**Comment by mhaid** [comment]
Okay, I'll have a look at it.
It's much harder when I can't test it myself, so sorry for the longer troubleshooting

**Comment by JerryVdV** [comment]
No problem, I can imagine the challenges indeed.
Happy to help either way and really appreciate the effort (where is that donate link ;))

**Comment by mhaid** [comment]
Thats kind of you, hopefully we'll solve the issue soon ;)
Just uploaded a new version

**Comment by JerryVdV** [comment]
Let me see which errors it gave. 

The log:
5bb4d173-f45e-4c05-aee5-bbaab3dbf763

**Comment by mhaid** [comment]
I uploaded a new version (3.1.4). Should all be working now :)

**Comment by JerryVdV** [comment]
Very happy, thanks! My already added TV is working again. Do you have a donate link? I’d like to buy you a drink!

When adding a new one the following error is displayed:
![17AE44BD-3E99-413C-BA66-3FF8BB3E6071](https://user-images.githubusercontent.com/29510796/107862821-d336fc80-6e4f-11eb-8a66-d8195be247bb.jpeg)

**Comment by mhaid** [comment]
Version 3.2.0 should now fix the issue :)
It also adds a better detection of IP-changes via MAC-Discovery and two new Flow-Actions for switching the TVs-inputs. Maybe it's helpful for you too


Please don't feel that you have to donate, but if you really want to, I would of course appreciate it! paypal.me/MorrisHaid

**Comment by JerryVdV** [comment]
Thanks, adding a new device is working again. The only thing that’s not working is turning on the tv.(Not a big deal for me, but might be good to know).

5242f73d-c8f1-4cb9-98c3-90b4c6ea7c58

-
As for the drink, you deserve it! ;-)

![BE8E1966-1A02-4387-9B32-EF3565BE900E](https://user-images.githubusercontent.com/29510796/107877985-f5705f00-6ecf-11eb-9f22-299bab9740c9.png)
![D041AF9E-ECA7-43B5-AF96-CD19E944E042](https://user-images.githubusercontent.com/29510796/107877988-f86b4f80-6ecf-11eb-8116-bb0488532eb5.png)

**Comment by mhaid** [comment]
Cheers, I appreciate it!

I just integrated the Wake on LAN functionality to the app.
My TV unfortunatly doesn't support it, but if yours do, feel free to test it out. You can check that either in the manual or with the Panasonic "TV remote 2"-App

Wake on LAN is being issued when the TV is shown as "OFF" in the homey app and you turn it on via the homey app.
Hope all works :)

**Comment by Martinbugel** [comment]
Hello,

Is it possible to add a flow with commands?
I need the enter key to go from the home screen to full screen.

Thanks

**Comment by JerryVdV** [comment]
> Cheers, I appreciate it!
> 
> I just integrated the _Wake on LAN_ functionality to the app.
> My TV unfortunatly doesn't support it, but if yours do, feel free to test it out. You can check if it is supportet either in the manual or with the Panasonic _"TV remote 2"_-App
> 
> _Wake on LAN_ is being used when the TV is shown as "OFF" in the homey app and you turn it on via the homey app.
> Hope all works :)

Happy customer here! So feel free to close off this issue as soon as you feel like it.
Many thanks again!

**Comment by mhaid** [comment]
@JerryVdV 
Great, happy to hear that :) Does the feature work properly?

@Martinbugel 
Thats possible, I'll notify you when I implemented it

**Comment by mhaid** [comment]
@Martinbugel
The feature is now implemented (Version >=3.4.0) :)

@JerryVdV 
I also added more stability to the WakeOnLAN feature. Now it's sending five packages with 0.5 Second delay, so the TV is more likely to hear one of them.

**Comment by Martinbugel** [comment]
Thanks! Is it possible to add the option hdm1 hdmi2 av enz in flows? Because the start input isn't always the same.

**Comment by JerryVdV** [comment]
> @Martinbugel
> The feature is now implemented (Version >=3.4.0) :)
> 
> @JerryVdV
> I also added more stability to the WakeOnLAN feature. Now it's sending five packages each with a 0.5 Second delay, so the TV is more likely to hear one of them.

Thanks, it’s working here! 👍🏽

**Comment by mhaid** [comment]
Great! I'll close the issue than.

@Martinbugel I'm afraid at the moment I can't think of a suitable way to implement this feature. As far as I know, the Panasonic TV does not support the query of the selected input nor a specific _set input to e.g. HDMI_ query. The official app also unfortunatly doesn't support it.
As soon as I or someone else has an idea how this can work, I will add it.
